### ISSUE TITLE
Adicionar ícones com links para as redes sociais no rodapé

### ISSUE THREAD

**Issue by DamascenoRafael** [caronae/caronae-site#2]
No rodapé de cada página deverá existir os links para as redes sociais do Caronaê. No `index.html` este rodapé irá substituir as duas linhas que falam sobre o Facebook e o YouTube no final da página.

O visual esperado são os ícones simples das redes sociais (no caso do Facebook, por exemplo, seria somente o "f" sem nenhum quadrado ou círculo em volta) em tom cinza, e quando o mouse estiver acima do ícone ele ser alterado para a cor correspondente da rede.

As redes sociais que devem ser exibidas são:
Facebook: https://www.facebook.com/redecaronae 
Instagram: https://www.instagram.com/redecaronae/ 
YouTube: https://www.youtube.com/channel/UCw3KFW1tZRxXShEowvVZLqQ 
GitHub: https://github.com/caronae/

**Comment by magnobiet** [comment]
@DamascenoRafael posso fazer. Os ícones podem ser em SVG?

Segue opções:

**Facebook**
https://www.flaticon.com/free-icon/facebook_733605

**Instagram**
https://www.flaticon.com/free-icon/instagram_733614

**YouTube**
https://www.flaticon.com/free-icon/youtube_733646

**GitHub**
https://www.flaticon.com/free-icon/github_733609

Para a cor cinza usar o mesmo tom dos textos `#6e6e70`?

---

Icons made by [Pixel perfect](https://www.flaticon.com/authors/pixel-perfect) from [www.flaticon.com](https://www.flaticon.com/) is licensed by [CC 3.0 BY](http://creativecommons.org/licenses/by/3.0/).

**Comment by DamascenoRafael** [comment]
@magnobiet claro, pode ser em SVG! Sobre os ícones eu estava pensando com estes estilos mesmo.

Não sei como pode fazer durante o hover do mouse. O Instagram, por exemplo, poderia permanecer cinza e depois quando quando mouse estiver em cima aparecer em sua versão colorida (como https://www.flaticon.com/free-icon/instagram_174855), o que acha?

Sobre o cinza pode manter esse mesmo ;)

**Comment by magnobiet** [comment]
@DamascenoRafael enviei o PR https://github.com/caronae/caronae-site/pull/4 incluindo os ícones.
