### ISSUE TITLE
Alterar parâmetro durante deploy do CircleCI de acordo com o ambiente de produção ou desenvolvimento

### ISSUE THREAD

**Issue by DamascenoRafael** [caronae/caronae-site#3]
No arquivo `.circleci/config.yml` é possível ver os passos que são seguidos para o deploy do site do Caronaê no ambiente de produção e desenvolvimento.
O arquivo `apple-app-site-association` permite que o aplicativo iOS do Caronaê seja aberto automaticamente ao abrir determinadas URLs do site.
Durante o deploy o parâmetro `appID` deve ser modificado de acordo com o ambiente para que somente o app de produção seja aberto pelo site de produção e somente o app de desenvolvimento seja aberto pelo site de desenvolvimento.

No ambiente de produção: `5JHLCV2DBL.br.ufrj.caronae`
No ambiente de desenvolvimento: `5JHLCV2DBL.br.ufrj.caronae-dev`

**Comment by JorgeMadson** [comment]
Opa legal, um repositório em português.
Vou ver do que se trata e tentar resolver essa issue!

**Comment by DamascenoRafael** [comment]
@JorgeMadson ótimo! Qualquer dúvida é só falar

**Comment by JorgeMadson** [comment]
Fiz uma solução simples pro problema, mas não testei em produção pq não uso o CI.

**Comment by JorgeMadson** [comment]
E não sei como relacionar o pull request com essa issues

**Comment by DamascenoRafael** [comment]
@JorgeMadson para relacionar o pull request basta colocar no comentário do PR uma `#` com o número da issue. O próprio github deve mostrar uma lista pra auto completar 😉

**Comment by DamascenoRafael** [comment]
Muito obrigado pela sua contribuição @JorgeMadson! Vou dar uma olhada depois :)

**Comment by macecchi** [comment]
Coloquei um comentário lá @JorgeMadson! Obrigado!

**Comment by macecchi** [comment]
closed by https://github.com/caronae/caronae-site/pull/6

**Comment by macecchi** [comment]
Deployado e funcionando:
```bash
➜  site git:(master) ✗ curl https://dev.caronae.org/apple-app-site-association
{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "5JHLCV2DBL.br.ufrj.caronae-dev",
        "paths": [
          "/c/*",
          "/carona/*"
        ]
      }
    ]
  }
}
```
```
➜  site git:(master) ✗ curl https://caronae.org/apple-app-site-association
{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "5JHLCV2DBL.br.ufrj.caronae",
        "paths": [
          "/c/*",
          "/carona/*"
        ]
      }
    ]
  }
}
```
